### ISSUE TITLE
Error pulling server from Discord.

### ISSUE THREAD

**Issue by DanyBv98** [CannibalVox/McDiscord#12]
I got this error after using the /discord-server command .

```
[23:55:55] [Thread-77/ERROR] [FML/]: Error pulling server from Discord.
java.io.IOException: Server returned HTTP response code: 403 for URL: https://discordapp.com/api/servers/******************/widget.json
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_66]
        at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source) ~[?:1.8.0_66]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_66]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_66]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_66]
        at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_66]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_66]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_66]
        at net.technicpack.mcdiscord.discord.api.http.HttpDiscordApi.getRestObject(HttpDiscordApi.java:177) ~[HttpDiscordApi.class:?]
        at net.technicpack.mcdiscord.discord.api.http.HttpDiscordApi.getRestObject(HttpDiscordApi.java:162) ~[HttpDiscordApi.class:?]
        at net.technicpack.mcdiscord.discord.api.http.HttpDiscordApi.synchronousGetServer(HttpDiscordApi.java:73) [HttpDiscordApi.class:?]
        at net.technicpack.mcdiscord.discord.api.http.HttpDiscordApi$1.run(HttpDiscordApi.java:52) [HttpDiscordApi$1.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
```

**Comment by DanyBv98** [comment]
My fault, sorry... Didn't enable the widget ...
