### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by RhysDam** [CannibalVox/McDiscord#9]
[12:38:14] [Thread-9141/ERROR]: Error pulling server from Discord.
java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_60]
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_60]
    at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[?:1.8.0_60]
    at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_60]
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[?:1.8.0_60]
    at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[?:1.8.0_60]
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973) ~[?:1.8.0_60]
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930) ~[?:1.8.0_60]
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[?:1.8.0_60]
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_60]
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_60]
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_60]
    at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704) ~[?:1.8.0_60]
    at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[?:1.8.0_60]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535) ~[?:1.8.0_60]
    at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) ~[?:1.8.0_60]
    at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432) ~[?:1.8.0_60]
    at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430) ~[?:1.8.0_60]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_60]
    at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782) ~[?:1.8.0_60]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429) ~[?:1.8.0_60]
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_60]
    at net.technicpack.mcdiscord.discord.api.http.HttpDiscordApi.getRestObject(HttpDiscordApi.java:177) ~[HttpDiscordApi.class:?]
    at net.technicpack.mcdiscord.discord.api.http.HttpDiscordApi.getRestObject(HttpDiscordApi.java:162) ~[HttpDiscordApi.class:?]
    at net.technicpack.mcdiscord.discord.api.http.HttpDiscordApi.synchronousGetServer(HttpDiscordApi.java:73) [HttpDiscordApi.class:?]
    at net.technicpack.mcdiscord.discord.api.http.HttpDiscordApi$1.run(HttpDiscordApi.java:52) [HttpDiscordApi$1.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

The errors doesn't seem to stop the mod from working, but is being produced every now and then in console.

Let me know if you want me to provide more information.

**Comment by chezpaul** [comment]
Getting the same error I think
KCauldron, 1.7.10 with Forge 1492

http://pastebin.com/hSG5ZS90

**Comment by chezpaul** [comment]
Is anyone here?
